[manifest]
version = "1.0.0"
dump_lua = true
priority = 150

[[patches]]
[patches.pattern]
target = "engine/save_manager.lua"
pattern = "save_string = love.data.compress('string', 'deflate', save_string, 1)"
position = "at"
payload = '''
local stopgap_config = get_compressed("config/stopgap.jkr")
local level = stopgap_config and stopgap_config["compression_level"] or 9
save_string = love.data.compress('string', 'deflate', save_string, level)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/string_packer.lua"
pattern = "function STR_PACK(data, recursive)"
position = "at"
payload = '''
function VANILLA_STR_PACK(data, recursive)
'''
match_indent = true

[[patches]]
[patches.module]
source = "src/string_packer.lua"
before = "engine/string_packer.lua"
name = "stopgap/string_packer"

[[patches]]
[patches.pattern]
target = "engine/string_packer.lua"
pattern = "function compress_and_save(_file, _data)"
position = "before"
payload = '''
require "stopgap/string_packer"
'''
match_indent = true